GET http://localhost:3001/

### get all users
GET http://localhost:3001/api/users

### get all towns
GET http://localhost:3001/api/users/town

### get single user
GET http://localhost:3001/api/users/1

### delet a user
DELETE http://localhost:3001/api/users/2

###
GET https://jsonplaceholder.typicode.com/users

### Create user
POST http://localhost:3001/api/users
Content-Type: application/json

{

    "name": "Mike", "town": "Kazkur", "isDriver": false

}